article/urls.py
from django.urls import path

from . import views

app_name = 'article'
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:pk>/', views.detail, name='detail'),
#     path('archives/<int:year>/<int:month>', views.archives, name='archives'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('tag/<int:pk>', views.TagView.as_view(), name='tag'),
    # path('search/', views.search, name='search')
    # path('add', views.add, name='add')
]

# 配置全局404页面
hander404 = 'views.page_not_found'

# 配置全局505页面
hander505 = 'views.page_errors'

blo/urls.py
from django.contrib import admin
from django.urls import path, include

from article.feeds import AllArticlesRssFeed
# import xawdmin
from beatemail import views as email_views

urlpatterns = [
    # path('all/rss/', AllArticlesRssFeed(), name='rss'),
    # path('article/', include('article.urls')),
    # path('comments/', include('comments.urls')),
    # path('admin/', admin.site.urls),
    # path('search/', include('haystack.urls'))

    path('all/rss/', AllArticlesRssFeed(), name='rss'),
    path('', include('article.urls')),
    path('', include('comments.urls')),
    path('lainly_admin/', admin.site.urls),
    path('search/', include('haystack.urls')),
    # path('xadmin/', xadmin.site.urls),
    path('email/', email_views.index, name='email'),
    path('summernote/', include('django_summernote.urls')),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
	path('article/<int:pk>', views.post_comment, name='post_comment')
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import markdown
from django.utils.html import strip_tags


class Tag(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class Article(models.Model):
	title = models.CharField(max_length=120)
	body = models.TextField()
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()
	read_times = models.PositiveIntegerField(default=0)
	summry = models.CharField(max_length=400, blank=True)
	tags = models.ManyToManyField(Tag, blank=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	updating = models.IntegerField(choices=((0, "No"),(1, "YES")), default=0)	

	def __str__(self):
		return self.title


	def get_absolute_url(self):
		"""
		in html ,using 
			<a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
			to replace:

		<a href="{% url 'article:detail' article.id %}">{{ article.title }}</a>
		"""
		return reverse('article:detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['-created_time']

	def increase_read_times(self):
		self.read_times += 1
		self.save(update_fields=['read_times'])

	def save(self, *args, **kwargs):
		if not self.summry:
			md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
			self.summry = strip_tags(md.convert(self.body))[:200]
		super(Article, self).save(*args, **kwargs)

comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    article = models.ForeignKey('article.Article', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

article/forms.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

# Apply summernote to specific fields.
class SomeForm(forms.Form):
    foo = forms.CharField(widget=SummernoteWidget())  # instead of forms.Textarea

# If you don't like <iframe>, then use inplace widget
# Or if you're using django-crispy-forms, please use this.
class AnotherForm(forms.Form):
    bar = forms.CharField(widget=SummernoteInplaceWidget())

class FormFromSomeModel(forms.ModelForm):
    class Meta:
        model = SomeModel
        widgets = {
            'foo': SummernoteWidget(),
            'bar': SummernoteInplaceWidget(),
        }

article/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Tag
from comments.forms import CommentForm
import markdown
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from django.views.generic import ListView, DetailView

# chinese
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

# search
from django.db.models import Q 

from .tasks import incr_readtimes

# def index(requset):
# 	# article_list = Article.objects.all().order_by('-created_time')
# 	article_list = Article.objects.all() # set in meta using desc order
# 	context = {
# 		'article_list': article_list
# 	}
# 	return render(requset, 'article/index.html', context)


class IndexView(ListView):
	model = Article
	template_name = 'article/index.html'
	context_object_name = 'article_list'
	paginate_by = 7



# def detail(requset, pk):
# 	article = get_object_or_404(Article, pk=pk)
# 	article.increase_read_times()
# 	article.body = markdown.markdown(article.body,
# 					extensions=[
# 					'markdown.extensions.extra',
# 					'markdown.extensions.codehilite',
# 					'markdown.extensions.toc',
# 					])
	
# 	form = CommentForm()
# 	comment_list = article.comment_set.all()
# 	context = {
# 		'article': article,
# 		'form': form,
# 		'comment_list': comment_list
# 	}
# 	return render(requset, 'article/detail.html', context)

class ArticleDetailView(DetailView):
	model = Article
	template_name = 'article/detail.html'
	context_object_name = 'article'

	def get(self, request, *args, **kwargs):
		# get 方法的调用看成是 detail 视图函数的调用
		# get 方法返回的是一个 HttpResponse 实例
		# 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
		# 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
		response = super(ArticleDetailView, self).get(request, *args, **kwargs)

		# 将文章阅读量 +1
		# 注意 self.object 的值就是被访问的文章 post
		# self.object.increase_read_times()

		# change to celery
		incr_readtimes.delay(self.object.id)

		# 视图必须返回一个 HttpResponse 对象
		return response

	def get_object(self, queryset=None):
		# 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
		article = super(ArticleDetailView, self).get_object(queryset=None)
		# article.body = markdown.markdown(article.body,
		# 								extensions=[
		# 								'markdown.extensions.extra',
		# 								'markdown.extensions.codehilite',
		# 								'markdown.extensions.toc',
		# 								])
		md = markdown.Markdown(extensions=[
								'markdown.extensions.extra',
								'markdown.extensions.codehilite',
								'markdown.extensions.toc',
								TocExtension(slugify=slugify),
								])
		article.body = md.convert(article.body)
		article.toc = md.toc
		return article

	def get_context_data(self, **kwargs):
		# 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
		# 还要把评论表单、post 下的评论列表传递给模板。
		context = super(ArticleDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
		    'form': form,
		    'comment_list': comment_list
		}) # python dict method
		return context



# def archives(request, year, month):
#     article_list = Article.objects.filter(created_time__year=year,
# 											created_time__month=month
# 											).order_by('-created_time')
#     context = {
# 		'article_list': article_list
# 	}
#     return render(request, 'article/index.html', context)

class ArchivesView(ListView):
	"""
	覆写了父类的 get_queryset 方法。该方法默认获取指定模型的全部列表数据。
	为了获取指定分类下的文章列表数据，我们覆写该方法，改变它的默认行为。
	首先是需要根据从 URL 中捕获的分类 id（也就是 pk）获取分类，
	这和 category 视图函数中的过程是一样的。不过注意一点的是，在类视图中，
	从 URL 捕获的命名组参数值保存在实例的 kwargs 属性（是一个字典）里，
	非命名组参数值保存在实例的 args 属性（是一个列表）里。
	所以我们使了 self.kwargs.get('pk') 来获取从 URL 捕获的分类 id 值。
	然后我们调用父类的 get_queryset 方法获得全部文章列表，
	紧接着就对返回的结果调用了 filter 方法来筛选该分类下的全部文章并返回。
	"""
	model = Article
	template_name = 'article/archives.html'
	context_object_name = 'article_list'

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
																created_time__month=month)
class TagView(ListView):
	model = Article
	template_name = 'article/tags.html'
	context_object_name = 'article_list'

	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
	q = request.GET.get('q')
	error_msg = ''

	if not q:
		error_msg = "请输入关键词"
		return render(request, 'article/Index.html', {'error_msg':error_msg})

	article_list = Article.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
	return render(request, 'article/index.html', {'error_msg':error_msg, 'article_list':article_list})

def page_not_found(request):
    return render(request, '404.html')

def page_errors(request):
    return render(request, '500.html')

# from django.shortcuts import HttpResponse
# from article import tasks
# def add(request):
# 	ans = tasks.add.delay(1, 2)
# 	print('running...')
# 	print('1 add 2 is', ans.get(timeout=1))
# 	return HttpResponse(ans.get(timeout=1))

article/templates/article/archives.html
{% extends "article/layout.html" %}

{% block title %}Archives{% endblock %}

{% block body %}

{% for article in article_list %}
    <h3><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></h3>
    {{article.summry}}
{% endfor %}



{% endblock %}

article/templates/article/detail.html
{% extends "article/layout.html" %}



{% block title %}Blog {% endblock %}

{% block body %}

<h1><p class="a-chinese">{{ article.title }}</p></h1>

{{ article.read_times }} Read.&nbsp;&nbsp;
{{ article.comment_set.count }} {% if article.comment_set.count == 0 %} Comment.{% else %}Comments.{% endif %}&nbsp;&nbsp;
{{ article.created_time|date:"Y/m/d" }} Created.&nbsp;&nbsp;
Last modified on {{ article.modified_time|date:"F j, Y" }}&nbsp;&nbsp;


<p>
{% for tag in article.tags.all %}<a href="{% url 'article:tag' tag.pk %}" class="a-chinese">{{ tag.name }}</a>&nbsp;/&nbsp;{% endfor %}</p>

<hr>

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">Catalogue:</h3>
        <p class="a-chinese">{{ article.toc|safe }}</p>
    </div>
    <hr>
{% endblock toc %}

<div class="a-chinese">
{{ article.body |safe}}
</div>

<hr>

<ul class="comment-list list-unstyled">
<h3>Comments({{ article.comment_set.count }}):</h3>
  {% for comment in comment_list %}
  <li class="comment-item">
    <span class="nickname"><a href="mailto:comment.email" style="color: 
            color: #8470FF;">@{{ comment.name }}</a></span>
    <time class="submit-date">{{ comment.created_time }}</time>
    <div class="text">
      {{ comment.text }}
    </div>
  </li>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>




<hr>

<form action="{% url 'comments:post_comment' article.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">Name：   </label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">Email：  </label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">URL：    </label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">Comment：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">Submit</button>
    </div>
  </div>    <!-- row -->
</form>




{% endblock %}



{% block tag %}

{% endblock %}

article/templates/article/index.html
{% extends "article/layout.html" %}
{% block title %}Blog {% endblock %}

{% block body %}
  {% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}

  {% for article in article_list %}
    <div class=entry-overview>
      <div class=date>
        <ul>
          <li class=date >{{ article.created_time|date:"F j, Y" }}</li>
          <li class=by >by {{ article.author }}</li>
          <li class=post > {{ article.read_times }} read</li>
        </ul>
      </div>

      <div class=detail>
      <h1><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></h1>
        {% if article.summry %}
        <div class=summary>{{ article.summry }}<br><a href="{% url 'article:detail' article.id %}">Read more -></a></div>
        {% endif %}
      </div>
    </div>
  {% endfor %}


  {% if is_paginated %}
  <div class=pagination>
    {% if page_obj.has_previous %}
       <a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a>
    {% else %}
      <span class=disabled>&laquo; Prev</span>
    {% endif %} — <strong>{{ page_obj.number }} / {{ paginator.num_pages }}</strong> — 

    {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
    {% else %}
      <span class=disabled>Next &raquo;</span>
    {% endif %}
  </div>
  {% endif%}


{% endblock %}
{% block tag %}

{% endblock %}

article/templates/article/layout.html
{% load staticfiles %}
{% load article_tags %}
<!doctype html>
<html>
  <head>
    <meta charset=utf-8>

    <link rel="stylesheet" type="text/css" href="{% static 'article/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'article/github.css' %}">
    <link rel="shortcut icon" href="{% static 'article/favicon.ico' %}">
    <style>
        span.highlighted {
            color: #8470FF;
        }
    </style>
  <title>{% block title %}Home{% endblock %} - lainly</title>

  </head>
  <body>
    <div class=container>
      <div class=header>
          <a href="{% url 'article:index' %}">Lainly </a> - 别急，我们终将爆发
      </div>
      <div class=navigation>
      

      </div>


      <div class=main>
        <div class=page>

        </div>

        <div class=page-index>
          <div class=body >

            {% block body %}

            {% block toc %}
            {% endblock %}
            
            {% endblock %}

          </div>
        </div>

        <div class=tag>
        <hr>

        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
          <input type="search" name="q" placeholder="搜索" required>
          <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>

        <hr>

        
        <div>
          <h3>Updating Articles:</h3>
          {% get_update_articles as update_article_list %}
            {% for article in update_article_list %}
            <ul><li>
              &raquo; <a href="{{ article.get_absolute_url }}" class="a-article">{{ article.title }}</a>
            </li></ul>
           {% empty %}
            No Article Here.
            {% endfor %}

        </div>



        <hr>


        <div>
          <h3>New Articles:</h3>
          {% get_recent_articles as recent_article_list %}
            {% for article in recent_article_list %}
            <ul><li>
              &raquo; <a href="{{ article.get_absolute_url }}" class="a-article">{{ article.title }}</a>
            </li></ul>
            {% empty %}
            No Article Here.
            {% endfor %}
       
        </div>


        <hr>


        <div>
          <h3>Archives:</h3>
          {% archives as date_list %}
          
            {% for date in date_list %}
            <ul>
            <li>
              
            <a href="{% url 'article:archives' date.year date.month %}" class="a-date">
            {{ date.year }} 年 {{ date.month }} 月</a>
            </li>
            </ul>

            {% empty %}
            No Archive Here.
            {% endfor %}
        </div>

        <hr>

        <div>
          <h3>Tag Cloud:</h3>
          {% get_tags as tag_list %}
          <ul>
            {% for tag in tag_list %}
            <li>
              <a href="{% url 'article:tag' tag.pk %}" class=tag-{{forloop.counter}}>{{ tag.name }}</a>
            </li>
            {% empty %}
            No Tag Here.
            {% endfor %}
          </ul>
        </div>

        <hr>

        <div class="rss">
          <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
        </div>


        </div>
      </div>


      <div class=footer>
        <p>&copy; 2017- &nbsp; &nbsp;  by Lainly.
        <p>
          Contact me via <a href="mailto:lainlyyt@126.com">mail</a>,
          <a href="http://weibo.com/lainly" target="_blank">weibo</a>,
          or
          <a href="http://github.com/lainkm" target="_blank">github</a>.
        <p>
      </div>
    </div>
  </body>
</html>

article/templates/article/tags.html
{% extends "article/layout.html" %}

{% block title %}tag{% endblock %}

{% block body %}

{% for article in article_list %}
    <h1><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></h1>
    {{article.summry}}
{% endfor %}



{% endblock %}